- name: Add GPG keys elasticsearch
  ansible.builtin.shell:
    cmd: curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |sudo gpg --dearmor --yes -o /usr/share/keyrings/elastic.gpg

- name: Install .deb package elasticsearch
  ansible.builtin.apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb

- name: Update elasticsearch config
  ansible.builtin.template:
    src: elasticsearch.standalone.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0644
  notify: 
  - Daemon reload
  - Start and enable elasticsearch

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: Get elasticsearch status
  ansible.builtin.uri:
    url: http://localhost:9200/_cat/health
    return_content: yes
  register: elasticsearch_status

- name: Show elasticsearch status
  debug:
    msg: "{{ elasticsearch_status.content }}"