- name: Check node_exporter.service exists
  stat:
    path: /etc/systemd/system/node_exporter.service
  register: node_exporter_result

- name: Create group "node_exporter"
  ansible.builtin.group:
    name: node_exporter
    state: present
    system: true
  when: not node_exporter_result.stat.exists

- name: "Create user node_exporter"
  ansible.builtin.user:
    name: node_exporter
    create_home: false
    system: true
    shell: /sbin/nologin
    groups: node_exporter
    state: present
  when: not node_exporter_result.stat.exists

- name: Create a directory /etc/node_exporter
  ansible.builtin.file:
    path: /etc/node_exporter
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: '0774'
  when: not node_exporter_result.stat.exists

- name: Get and unarchive node_exporter package
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
  when: not node_exporter_result.stat.exists

- name: Copy bin node_exporter
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
    owner: node_exporter
    group: node_exporter
    mode: '0770'
  with_items:
    - /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
  when: not node_exporter_result.stat.exists

- name: Remove tmp package files
  ansible.builtin.file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
    state: absent
  when: not node_exporter_result.stat.exists

- name: Create service file node_exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: node_exporter
    group: node_exporter
    mode: 0644
  notify: 
  - Daemon reload
  - Start and enable node_exporter
  when: not node_exporter_result.stat.exists

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  when: not node_exporter_result.stat.exists