---
- name: Start and enable prometheus
  ansible.builtin.service:
    name: prometheus.service
    state: started
    enabled: yes

- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus.service
    state: restarted

- name: Start and enable alertmanager
  ansible.builtin.service:
    name: alertmanager.service
    state: started
    enabled: yes

- name: Restart alertmanager
  ansible.builtin.service:
    name: alertmanager.service
    state: restarted

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx.service
    state: started
    enabled: yes

- name: Restart nginx
  ansible.builtin.service:
    name: nginx.service
    state: restarted

- name: Start and enable grafana
  ansible.builtin.service:
    name: grafana-server.service
    state: started
    enabled: yes

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server.service
    state: restarted

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true